### ISSUE TITLE
Please make me a Contributor

### ISSUE THREAD

**Issue by jogmg** [CREDO23/AirBnB_clone_v4#1]
Please make me a contributor to the repo as soon as you can. Time is running out on the project and I have been really busy.
Sorry to disturb

**Comment by CREDO23** [comment]
Done

**Comment by jogmg** [comment]
I can’t seem to make changes to the branch. Please try managing the branch
protection rules. Go to settings in the repository, under code and
automation click branches. You should be able to see the branch protection
rule preventing me from making any changes. Thank you.
